name: migration
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - pip=24.0
  - pip:
      - openai==1.97.0
      - transformers==4.49.0
      - tree_sitter==0.21.3
      - antlr4-python3-runtime==4.13.2
      - antlr4-tools==0.2.1